# Install script for directory: /workdir/LexxHard-SensorControlBoard-Firmware/zephyr

# Set the install prefix
if(NOT DEFINED CMAKE_INSTALL_PREFIX)
  set(CMAKE_INSTALL_PREFIX "/usr/local")
endif()
string(REGEX REPLACE "/$" "" CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")

# Set the install configuration name.
if(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)
  if(BUILD_TYPE)
    string(REGEX REPLACE "^[^A-Za-z0-9_]+" ""
           CMAKE_INSTALL_CONFIG_NAME "${BUILD_TYPE}")
  else()
    set(CMAKE_INSTALL_CONFIG_NAME "")
  endif()
  message(STATUS "Install configuration: \"${CMAKE_INSTALL_CONFIG_NAME}\"")
endif()

# Set the component getting installed.
if(NOT CMAKE_INSTALL_COMPONENT)
  if(COMPONENT)
    message(STATUS "Install component: \"${COMPONENT}\"")
    set(CMAKE_INSTALL_COMPONENT "${COMPONENT}")
  else()
    set(CMAKE_INSTALL_COMPONENT)
  endif()
endif()

# Is this installation the result of a crosscompile?
if(NOT DEFINED CMAKE_CROSSCOMPILING)
  set(CMAKE_CROSSCOMPILING "TRUE")
endif()

# Set default install directory permissions.
if(NOT DEFINED CMAKE_OBJDUMP)
  set(CMAKE_OBJDUMP "/opt/toolchains/gcc-arm-none-eabi-10-2020-q4-major/bin/arm-none-eabi-objdump")
endif()

if(NOT CMAKE_INSTALL_LOCAL_ONLY)
  # Include the install script for each subdirectory.
  include("/workdir/LexxHard-SensorControlBoard-Firmware/build/zephyr/arch/cmake_install.cmake")
  include("/workdir/LexxHard-SensorControlBoard-Firmware/build/zephyr/lib/cmake_install.cmake")
  include("/workdir/LexxHard-SensorControlBoard-Firmware/build/zephyr/soc/arm/cmake_install.cmake")
  include("/workdir/LexxHard-SensorControlBoard-Firmware/build/zephyr/boards/cmake_install.cmake")
  include("/workdir/LexxHard-SensorControlBoard-Firmware/build/zephyr/subsys/cmake_install.cmake")
  include("/workdir/LexxHard-SensorControlBoard-Firmware/build/zephyr/drivers/cmake_install.cmake")
  include("/workdir/LexxHard-SensorControlBoard-Firmware/build/modules/CANopenNode/cmake_install.cmake")
  include("/workdir/LexxHard-SensorControlBoard-Firmware/build/modules/civetweb/cmake_install.cmake")
  include("/workdir/LexxHard-SensorControlBoard-Firmware/build/modules/cmsis/cmake_install.cmake")
  include("/workdir/LexxHard-SensorControlBoard-Firmware/build/modules/fatfs/cmake_install.cmake")
  include("/workdir/LexxHard-SensorControlBoard-Firmware/build/modules/altera/cmake_install.cmake")
  include("/workdir/LexxHard-SensorControlBoard-Firmware/build/modules/atmel/cmake_install.cmake")
  include("/workdir/LexxHard-SensorControlBoard-Firmware/build/modules/cypress/cmake_install.cmake")
  include("/workdir/LexxHard-SensorControlBoard-Firmware/build/modules/espressif/cmake_install.cmake")
  include("/workdir/LexxHard-SensorControlBoard-Firmware/build/modules/infineon/cmake_install.cmake")
  include("/workdir/LexxHard-SensorControlBoard-Firmware/build/modules/microchip/cmake_install.cmake")
  include("/workdir/LexxHard-SensorControlBoard-Firmware/build/modules/hal_nordic/cmake_install.cmake")
  include("/workdir/LexxHard-SensorControlBoard-Firmware/build/modules/nuvoton/cmake_install.cmake")
  include("/workdir/LexxHard-SensorControlBoard-Firmware/build/modules/hal_nxp/cmake_install.cmake")
  include("/workdir/LexxHard-SensorControlBoard-Firmware/build/modules/openisa/cmake_install.cmake")
  include("/workdir/LexxHard-SensorControlBoard-Firmware/build/modules/quicklogic/cmake_install.cmake")
  include("/workdir/LexxHard-SensorControlBoard-Firmware/build/modules/silabs/cmake_install.cmake")
  include("/workdir/LexxHard-SensorControlBoard-Firmware/build/modules/st/cmake_install.cmake")
  include("/workdir/LexxHard-SensorControlBoard-Firmware/build/modules/stm32/cmake_install.cmake")
  include("/workdir/LexxHard-SensorControlBoard-Firmware/build/modules/telink/cmake_install.cmake")
  include("/workdir/LexxHard-SensorControlBoard-Firmware/build/modules/ti/cmake_install.cmake")
  include("/workdir/LexxHard-SensorControlBoard-Firmware/build/modules/xtensa/cmake_install.cmake")
  include("/workdir/LexxHard-SensorControlBoard-Firmware/build/modules/libmetal/cmake_install.cmake")
  include("/workdir/LexxHard-SensorControlBoard-Firmware/build/modules/littlefs/cmake_install.cmake")
  include("/workdir/LexxHard-SensorControlBoard-Firmware/build/modules/loramac-node/cmake_install.cmake")
  include("/workdir/LexxHard-SensorControlBoard-Firmware/build/modules/lvgl/cmake_install.cmake")
  include("/workdir/LexxHard-SensorControlBoard-Firmware/build/modules/lz4/cmake_install.cmake")
  include("/workdir/LexxHard-SensorControlBoard-Firmware/build/modules/mbedtls/cmake_install.cmake")
  include("/workdir/LexxHard-SensorControlBoard-Firmware/build/modules/mcuboot/cmake_install.cmake")
  include("/workdir/LexxHard-SensorControlBoard-Firmware/build/modules/mcumgr/cmake_install.cmake")
  include("/workdir/LexxHard-SensorControlBoard-Firmware/build/modules/mipi-sys-t/cmake_install.cmake")
  include("/workdir/LexxHard-SensorControlBoard-Firmware/build/modules/nanopb/cmake_install.cmake")
  include("/workdir/LexxHard-SensorControlBoard-Firmware/build/modules/nrf_hw_models/cmake_install.cmake")
  include("/workdir/LexxHard-SensorControlBoard-Firmware/build/modules/open-amp/cmake_install.cmake")
  include("/workdir/LexxHard-SensorControlBoard-Firmware/build/modules/openthread/cmake_install.cmake")
  include("/workdir/LexxHard-SensorControlBoard-Firmware/build/modules/segger/cmake_install.cmake")
  include("/workdir/LexxHard-SensorControlBoard-Firmware/build/modules/sof/cmake_install.cmake")
  include("/workdir/LexxHard-SensorControlBoard-Firmware/build/modules/tflite-micro/cmake_install.cmake")
  include("/workdir/LexxHard-SensorControlBoard-Firmware/build/modules/tinycbor/cmake_install.cmake")
  include("/workdir/LexxHard-SensorControlBoard-Firmware/build/modules/tinycrypt/cmake_install.cmake")
  include("/workdir/LexxHard-SensorControlBoard-Firmware/build/modules/TraceRecorder/cmake_install.cmake")
  include("/workdir/LexxHard-SensorControlBoard-Firmware/build/modules/extradrivers/cmake_install.cmake")
  include("/workdir/LexxHard-SensorControlBoard-Firmware/build/zephyr/kernel/cmake_install.cmake")
  include("/workdir/LexxHard-SensorControlBoard-Firmware/build/zephyr/cmake/flash/cmake_install.cmake")
  include("/workdir/LexxHard-SensorControlBoard-Firmware/build/zephyr/cmake/usage/cmake_install.cmake")
  include("/workdir/LexxHard-SensorControlBoard-Firmware/build/zephyr/cmake/reports/cmake_install.cmake")

endif()

