#!/usr/bin/env python3
# Copyright (c) 2026, LexxPluss Inc.
# All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
#
# Packs the VL53L7CX device-firmware blob into the record the firmware reads out of
# storage_partition, and emits the accept-list header the firmware is built against.
#
# Offline generation tool, so Python: it produces artefacts, it is not in the image and it is not a
# test. The format it writes is specified in docs/tof_l7_blob_record.md and read by
# lexxpluss_apps/src/tof_l7_blob_record.cpp.
#
# Two things it emits, and the pairing is the point:
#
#   the record image   flashed at storage_partition (0x20000 on lexxpluss_scb)
#   the accept-list    one or more length/SHA-256 identities, compiled INTO the image
#
# The firmware therefore refuses a blob that is intact but not the one it was built for. That
# refusal is separate from "the bytes are damaged" because the two send whoever reads them to
# different places, and only one of them means the flash is broken.
#
# The `golden` mode emits a small complete record as a C header for the host test
# suite. That is what keeps this script and the C++ reader from drifting: the suite verifies bytes
# THIS script produced, so a change to either side that breaks the agreement fails a test rather
# than a board.

import argparse
import hashlib
import pathlib
import re
import struct
import sys
import zlib

MAGIC = b"L7B1"
FORMAT_VERSION = 2
HEADER_SIZE = 64
DIGEST_SIZE = 32
RESERVED_LEN = 16
COMMIT_MARKER = b"L7OK"

# lexxpluss_scb: storage_partition, 128 KiB at 0x20000. The one region no application code
# referenced, which is why the blob can live there at all.
DEFAULT_REGION_SIZE = 0x20000


def build_header(payload: bytes) -> bytes:
    digest = hashlib.sha256(payload).digest()
    head = struct.pack(
        "<4sHHI32s16s",
        MAGIC,
        FORMAT_VERSION,
        HEADER_SIZE,
        len(payload),
        digest,
        b"\x00" * RESERVED_LEN,
    )
    if len(head) != HEADER_SIZE - 4:
        raise SystemExit(f"header layout is {len(head) + 4} bytes, not {HEADER_SIZE}")
    return head + struct.pack("<I", zlib.crc32(head) & 0xFFFFFFFF)


def build_record(payload: bytes, region_size: int, committed: bool = True) -> bytes:
    if not payload:
        raise SystemExit("the payload is empty")
    if HEADER_SIZE + len(payload) + len(COMMIT_MARKER) > region_size:
        raise SystemExit(
            f"record is {HEADER_SIZE + len(payload) + len(COMMIT_MARKER)} bytes and the region is {region_size}: "
            "the blob does not fit"
        )
    record = build_header(payload) + payload
    # Golden tests consume a complete committed record. The pack command deliberately asks for an
    # uncommitted image and a separate marker file so the unsafe ordering (marker before read-back)
    # is not the easiest way to use the tool.
    return record + COMMIT_MARKER if committed else record


def c_bytes(data: bytes, per_line: int = 12) -> str:
    lines = []
    for i in range(0, len(data), per_line):
        chunk = ", ".join(f"0x{b:02x}" for b in data[i : i + per_line])
        lines.append(f"    {chunk},")
    return "\n".join(lines)


def read_payload(path: pathlib.Path, c_array: str | None) -> bytes:
    if c_array is None:
        return path.read_bytes()

    text = path.read_text()
    pattern = re.compile(
        rf"\bconst\s+uint8_t\s+{re.escape(c_array)}\s*\[\s*\]\s*=\s*\{{(.*?)\}}\s*;",
        re.DOTALL,
    )
    match = pattern.search(text)
    if match is None:
        raise SystemExit(f"C array {c_array!r} was not found in {path}")
    body = re.sub(r"/\*.*?\*/|//[^\n]*", "", match.group(1), flags=re.DOTALL)
    values = []
    for token in body.split(","):
        token = token.strip()
        if not token:
            continue
        try:
            value = int(token, 0)
        except ValueError as exc:
            raise SystemExit(f"unsupported token {token!r} in {c_array}") from exc
        if not 0 <= value <= 0xFF:
            raise SystemExit(f"value {value} in {c_array} is not one byte")
        values.append(value)
    if not values:
        raise SystemExit(f"C array {c_array!r} is empty")
    return bytes(values)


def expectation_header(payloads: list[tuple[bytes, str]]) -> str:
    entries = []
    for payload, source in payloads:
        digest = hashlib.sha256(payload).digest()
        entries.append(
            f"    // {source}\n"
            f"    {{{len(payload)}, {{\n{c_bytes(digest)}\n    }}}},"
        )
    return f"""/*
 * GENERATED by the L7 blob-record generator -- do not edit.
 *
 * What this firmware expects to find in storage_partition: the length and SHA-256 of the VL53L7CX
 * device-firmware payload it was built against. The blob itself is NOT here and must not be: it is
 * 84 KiB of vendor firmware and keeping it out of the signed image is the entire reason the record
 * exists.
 *
 * Every entry below is a compatibility claim and therefore requires a bench result with this ULD.
 */

#pragma once

#include <stddef.h>
#include <stdint.h>

#include "tof_l7_blob_record.hpp"

namespace lexxhard::tof_l7_blob {{

inline constexpr expectation kAcceptedPayloads[]{{
{chr(10).join(entries)}
}};

inline constexpr accept_list kAcceptedPayloadList{{
    kAcceptedPayloads,
    sizeof kAcceptedPayloads / sizeof kAcceptedPayloads[0],
}};

}}  // namespace lexxhard::tof_l7_blob
"""


def golden_header(payload: bytes) -> str:
    record = build_record(payload, DEFAULT_REGION_SIZE)
    digest = hashlib.sha256(payload).digest()
    return f"""/*
 * GENERATED by the L7 blob-record generator's golden mode -- do not edit.
 *
 * A complete, valid record, small enough to sit in a test binary. The suite verifies THESE bytes
 * with the production reader, which is what pins the generator and the reader together: if either
 * side changes its mind about the layout, a host test fails instead of a board.
 *
 * The payload is synthetic so this test stays small. The real vendor array is preserved once in the
 * upstream snapshot and is never duplicated into this test image.
 */

#pragma once

#include <stddef.h>
#include <stdint.h>

namespace lexxhard::tof_l7_blob::golden {{

inline constexpr size_t kPayloadLen{{{len(payload)}}};
inline constexpr size_t kRecordLen{{{len(record)}}};

inline constexpr uint8_t kPayloadDigest[32]{{
{c_bytes(digest)}
}};

// Header plus payload, exactly as the generator writes it to flash.
inline constexpr uint8_t kRecord[kRecordLen]{{
{c_bytes(record)}
}};

}}  // namespace lexxhard::tof_l7_blob::golden
"""


def synthetic_payload(length: int) -> bytes:
    """A payload with no runs and no symmetry, so an off-by-one in the reader shows up.

    Deliberately not zeros or a constant: a digest over 1024 zeros is identical to a digest over
    the same zeros read at the wrong offset, so a reader that skipped or repeated a chunk would
    still pass. Every byte here depends on its index.
    """
    return bytes(((i * 31) ^ (i >> 5) ^ 0xA5) & 0xFF for i in range(length))


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    sub = ap.add_subparsers(dest="mode", required=True)

    pack = sub.add_parser("pack", help="pack a vendor blob into a flashable record")
    pack.add_argument("blob", type=pathlib.Path, help="raw VL53L7CX_FIRMWARE payload")
    pack.add_argument(
        "--c-array",
        help="extract this uint8_t array from the input C header instead of treating it as raw bytes",
    )
    pack.add_argument(
        "--accept-blob",
        action="append",
        type=pathlib.Path,
        default=[],
        help="additional bench-proven payload accepted for rollback compatibility",
    )
    pack.add_argument("--out", type=pathlib.Path, help="uncommitted header+payload image")
    pack.add_argument(
        "--commit-marker-out",
        type=pathlib.Path,
        help="four bytes to write only after read-back verification",
    )
    pack.add_argument(
        "--expect-header",
        type=pathlib.Path,
        help="also write the signed-image accept-list header",
    )
    pack.add_argument("--region-size", type=lambda v: int(v, 0), default=DEFAULT_REGION_SIZE)
    pack.add_argument(
        "--check",
        action="store_true",
        help="verify the committed expectation header without modifying any output",
    )

    gold = sub.add_parser("golden", help="emit the golden record header for the host suite")
    gold.add_argument("--out", type=pathlib.Path, required=True)
    gold.add_argument("--payload-len", type=int, default=1024)
    gold.add_argument(
        "--check",
        action="store_true",
        help="compare with --out without modifying it",
    )

    args = ap.parse_args()

    if args.mode == "pack":
        if args.accept_blob and not args.expect_header:
            raise SystemExit("--accept-blob requires --expect-header")
        payload = read_payload(args.blob, args.c_array)
        accepted = [(payload, args.blob.name)]
        seen = {hashlib.sha256(payload).digest()}
        for path in args.accept_blob:
            extra = path.read_bytes()
            digest_bytes = hashlib.sha256(extra).digest()
            if digest_bytes in seen:
                continue
            seen.add(digest_bytes)
            accepted.append((extra, path.name))
        rendered_expectation = expectation_header(accepted)

        if args.check:
            if args.expect_header is None:
                raise SystemExit("pack --check requires --expect-header")
            if (
                not args.expect_header.exists()
                or args.expect_header.read_text() != rendered_expectation
            ):
                print(f"stale generated artefact: {args.expect_header}", file=sys.stderr)
                return 1
            print(f"blob expectation is current: {args.expect_header}")
            return 0

        if args.out is None or args.commit_marker_out is None:
            raise SystemExit("pack requires --out and --commit-marker-out")
        record = build_record(payload, args.region_size, committed=False)
        args.out.write_bytes(record)
        args.commit_marker_out.write_bytes(COMMIT_MARKER)
        digest = hashlib.sha256(payload).hexdigest()
        print(f"payload  {len(payload)} B  sha256 {digest}")
        print(f"record   {len(record)} B uncommitted -> {args.out}")
        print(
            f"commit   offset {len(record)} ({len(COMMIT_MARKER)} B) -> {args.commit_marker_out}"
        )
        print(
            f"region   {args.region_size} B  "
            f"({args.region_size - len(record) - len(COMMIT_MARKER)} B spare)"
        )
        if args.expect_header:
            args.expect_header.write_text(rendered_expectation)
            print(f"expect   -> {args.expect_header}")
        return 0

    rendered = golden_header(synthetic_payload(args.payload_len))
    if args.check:
        if not args.out.exists() or args.out.read_text() != rendered:
            print(f"stale generated artefact: {args.out}", file=sys.stderr)
            return 1
        print(f"golden record is current: {args.out}")
        return 0
    args.out.write_text(rendered)
    print(f"golden record ({args.payload_len} B payload) -> {args.out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
