#!/usr/bin/env python3
# Copyright (c) 2026, LexxPluss Inc.
# All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
#
# Packs the VL53L7CX device-firmware blob into the record the firmware reads out of
# storage_partition, and emits the expectation header the firmware is built against.
#
# Offline generation tool, so Python: it produces artefacts, it is not in the image and it is not a
# test. The format it writes is specified in docs/tof_l7_blob_record.md and read by
# lexxpluss_apps/src/tof_l7_blob_record.cpp.
#
# Two things it emits, and the pairing is the point:
#
#   the record image   flashed at storage_partition (0x20000 on lexxpluss_scb)
#   the expectation    a header with the payload's length and SHA-256, compiled INTO the image
#
# The firmware therefore refuses a blob that is intact but not the one it was built for. That
# refusal is separate from "the bytes are damaged" because the two send whoever reads them to
# different places, and only one of them means the flash is broken.
#
# The `golden` mode emits a small record plus its expectation as a C header for the host test
# suite. That is what keeps this script and the C++ reader from drifting: the suite verifies bytes
# THIS script produced, so a change to either side that breaks the agreement fails a test rather
# than a board.

import argparse
import hashlib
import pathlib
import struct
import sys
import zlib

MAGIC = b"L7B1"
FORMAT_VERSION = 1
HEADER_SIZE = 64
DIGEST_SIZE = 32
RESERVED_LEN = 16

# lexxpluss_scb: storage_partition, 128 KiB at 0x20000. The one region no application code
# referenced, which is why the blob can live there at all.
DEFAULT_REGION_SIZE = 0x20000


def build_header(payload: bytes) -> bytes:
    digest = hashlib.sha256(payload).digest()
    head = struct.pack(
        "<4sHHI32s16s",
        MAGIC,
        FORMAT_VERSION,
        HEADER_SIZE,
        len(payload),
        digest,
        b"\x00" * RESERVED_LEN,
    )
    if len(head) != HEADER_SIZE - 4:
        raise SystemExit(f"header layout is {len(head) + 4} bytes, not {HEADER_SIZE}")
    return head + struct.pack("<I", zlib.crc32(head) & 0xFFFFFFFF)


def build_record(payload: bytes, region_size: int) -> bytes:
    if not payload:
        raise SystemExit("the payload is empty")
    if HEADER_SIZE + len(payload) > region_size:
        raise SystemExit(
            f"record is {HEADER_SIZE + len(payload)} bytes and the region is {region_size}: "
            "the blob does not fit"
        )
    return build_header(payload) + payload


def c_bytes(data: bytes, per_line: int = 12) -> str:
    lines = []
    for i in range(0, len(data), per_line):
        chunk = ", ".join(f"0x{b:02x}" for b in data[i : i + per_line])
        lines.append(f"    {chunk},")
    return "\n".join(lines)


def expectation_header(payload: bytes, source: str) -> str:
    digest = hashlib.sha256(payload).digest()
    return f"""/*
 * GENERATED by scripts/gen_l7_blob_record.py -- do not edit.
 *
 * What this firmware expects to find in storage_partition: the length and SHA-256 of the VL53L7CX
 * device-firmware payload it was built against. The blob itself is NOT here and must not be: it is
 * 84 KiB of vendor firmware and keeping it out of the signed image is the entire reason the record
 * exists.
 *
 * source: {source}
 */

#pragma once

#include <stddef.h>
#include <stdint.h>

namespace lexxhard::tof_l7_blob {{

inline constexpr size_t kExpectedPayloadLen{{{len(payload)}}};

inline constexpr uint8_t kExpectedPayloadDigest[32]{{
{c_bytes(digest)}
}};

}}  // namespace lexxhard::tof_l7_blob
"""


def golden_header(payload: bytes) -> str:
    record = build_record(payload, DEFAULT_REGION_SIZE)
    digest = hashlib.sha256(payload).digest()
    return f"""/*
 * GENERATED by scripts/gen_l7_blob_record.py golden -- do not edit.
 *
 * A complete, valid record, small enough to sit in a test binary. The suite verifies THESE bytes
 * with the production reader, which is what pins the generator and the reader together: if either
 * side changes its mind about the layout, a host test fails instead of a board.
 *
 * The payload is synthetic. It has to be: the real one is vendor firmware that must not enter this
 * repository, and a test that needed it could not run.
 */

#pragma once

#include <stddef.h>
#include <stdint.h>

namespace lexxhard::tof_l7_blob::golden {{

inline constexpr size_t kPayloadLen{{{len(payload)}}};
inline constexpr size_t kRecordLen{{{len(record)}}};

inline constexpr uint8_t kPayloadDigest[32]{{
{c_bytes(digest)}
}};

// Header plus payload, exactly as the generator writes it to flash.
inline constexpr uint8_t kRecord[kRecordLen]{{
{c_bytes(record)}
}};

}}  // namespace lexxhard::tof_l7_blob::golden
"""


def synthetic_payload(length: int) -> bytes:
    """A payload with no runs and no symmetry, so an off-by-one in the reader shows up.

    Deliberately not zeros or a constant: a digest over 1024 zeros is identical to a digest over
    the same zeros read at the wrong offset, so a reader that skipped or repeated a chunk would
    still pass. Every byte here depends on its index.
    """
    return bytes(((i * 31) ^ (i >> 5) ^ 0xA5) & 0xFF for i in range(length))


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    sub = ap.add_subparsers(dest="mode", required=True)

    pack = sub.add_parser("pack", help="pack a vendor blob into a flashable record")
    pack.add_argument("blob", type=pathlib.Path, help="raw VL53L7CX_FIRMWARE payload")
    pack.add_argument("--out", type=pathlib.Path, required=True, help="record image to write")
    pack.add_argument(
        "--expect-header",
        type=pathlib.Path,
        help="also write the expectation header the firmware compiles in",
    )
    pack.add_argument("--region-size", type=lambda v: int(v, 0), default=DEFAULT_REGION_SIZE)

    gold = sub.add_parser("golden", help="emit the golden record header for the host suite")
    gold.add_argument("--out", type=pathlib.Path, required=True)
    gold.add_argument("--payload-len", type=int, default=1024)

    args = ap.parse_args()

    if args.mode == "pack":
        payload = args.blob.read_bytes()
        record = build_record(payload, args.region_size)
        args.out.write_bytes(record)
        digest = hashlib.sha256(payload).hexdigest()
        print(f"payload  {len(payload)} B  sha256 {digest}")
        print(f"record   {len(record)} B  -> {args.out}")
        print(f"region   {args.region_size} B  ({args.region_size - len(record)} B spare)")
        if args.expect_header:
            args.expect_header.write_text(expectation_header(payload, args.blob.name))
            print(f"expect   -> {args.expect_header}")
        return 0

    args.out.write_text(golden_header(synthetic_payload(args.payload_len)))
    print(f"golden record ({args.payload_len} B payload) -> {args.out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
