#derived from https://qiita.com/ucan-lab/items/4b02dec969df399253f7
name: Assign Label
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  assign-label:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/labeler@v5
        if: ${{ github.event.action == 'opened' }}
        with:
          configuration-path: .github/assign-label-rules.yml
